# Copyright 2013 Globo.com. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This file is generated automatically, please avoid editing it.

from flaskext.babel import lazy_gettext as _

country_choices = [
    ("United States", _("United States"))
    ("United Kingdom", _("United Kingdom"))
    ("Afghanistan", _("Afghanistan"))
    ("Albania", _("Albania"))
    ("Algeria", _("Algeria"))
    ("American Samoa", _("American Samoa"))
    ("Andorra", _("Andorra"))
    ("Angola", _("Angola"))
    ("Anguilla", _("Anguilla"))
    ("Antarctica", _("Antarctica"))
    ("Antigua and Barbuda", _("Antigua and Barbuda"))
    ("Argentina", _("Argentina"))
    ("Armenia", _("Armenia"))
    ("Aruba", _("Aruba"))
    ("Australia", _("Australia"))
    ("Austria", _("Austria"))
    ("Azerbaijan", _("Azerbaijan"))
    ("Bahamas", _("Bahamas"))
    ("Bahrain", _("Bahrain"))
    ("Bangladesh", _("Bangladesh"))
    ("Barbados", _("Barbados"))
    ("Belarus", _("Belarus"))
    ("Belgium", _("Belgium"))
    ("Belize", _("Belize"))
    ("Benin", _("Benin"))
    ("Bermuda", _("Bermuda"))
    ("Bhutan", _("Bhutan"))
    ("Bolivia", _("Bolivia"))
    ("Bosnia and Herzegovina", _("Bosnia and Herzegovina"))
    ("Botswana", _("Botswana"))
    ("Bouvet Island", _("Bouvet Island"))
    ("Brazil", _("Brazil"))
    ("British Indian Ocean Territory", _("British Indian Ocean Territory"))
    ("Brunei Darussalam", _("Brunei Darussalam"))
    ("Bulgaria", _("Bulgaria"))
    ("Burkina Faso", _("Burkina Faso"))
    ("Burundi", _("Burundi"))
    ("Cambodia", _("Cambodia"))
    ("Cameroon", _("Cameroon"))
    ("Canada", _("Canada"))
    ("Cape Verde", _("Cape Verde"))
    ("Cayman Islands", _("Cayman Islands"))
    ("Central African Republic", _("Central African Republic"))
    ("Chad", _("Chad"))
    ("Chile", _("Chile"))
    ("Christmas Island", _("Christmas Island"))
    ("Cocos (Keeling) Islands", _("Cocos (Keeling) Islands"))
    ("Colombia", _("Colombia"))
    ("Comoros", _("Comoros"))
    ("Congo", _("Congo"))
    ("Congo, The Democratic Republic of The", _("Congo, The Democratic Republic of The"))
    ("Cook Islands", _("Cook Islands"))
    ("Costa Rica", _("Costa Rica"))
    ("Cote D'ivoire", _("Cote D'ivoire"))
    ("Croatia", _("Croatia"))
    ("Cuba", _("Cuba"))
    ("Cyprus", _("Cyprus"))
    ("Czech Republic", _("Czech Republic"))
    ("Denmark", _("Denmark"))
    ("Djibouti", _("Djibouti"))
    ("Dominica", _("Dominica"))
    ("Dominican Republic", _("Dominican Republic"))
    ("Ecuador", _("Ecuador"))
    ("Egypt", _("Egypt"))
    ("El Salvador", _("El Salvador"))
    ("Equatorial Guinea", _("Equatorial Guinea"))
    ("Eritrea", _("Eritrea"))
    ("Estonia", _("Estonia"))
    ("Ethiopia", _("Ethiopia"))
    ("Falkland Islands (Malvinas)", _("Falkland Islands (Malvinas)"))
    ("Faroe Islands", _("Faroe Islands"))
    ("Fiji", _("Fiji"))
    ("Finland", _("Finland"))
    ("France", _("France"))
    ("French Guiana", _("French Guiana"))
    ("French Polynesia", _("French Polynesia"))
    ("French Southern Territories", _("French Southern Territories"))
    ("Gabon", _("Gabon"))
    ("Gambia", _("Gambia"))
    ("Georgia", _("Georgia"))
    ("Germany", _("Germany"))
    ("Ghana", _("Ghana"))
    ("Gibraltar", _("Gibraltar"))
    ("Greece", _("Greece"))
    ("Greenland", _("Greenland"))
    ("Grenada", _("Grenada"))
    ("Guadeloupe", _("Guadeloupe"))
    ("Guam", _("Guam"))
    ("Guatemala", _("Guatemala"))
    ("Guinea", _("Guinea"))
    ("Guinea-bissau", _("Guinea-bissau"))
    ("Guyana", _("Guyana"))
    ("Haiti", _("Haiti"))
    ("Heard Island and Mcdonald Islands", _("Heard Island and Mcdonald Islands"))
    ("Holy See (Vatican City State)", _("Holy See (Vatican City State)"))
    ("Honduras", _("Honduras"))
    ("Hong Kong", _("Hong Kong"))
    ("Hungary", _("Hungary"))
    ("Iceland", _("Iceland"))
    ("India", _("India"))
    ("Indonesia", _("Indonesia"))
    ("Iran, Islamic Republic of", _("Iran, Islamic Republic of"))
    ("Iraq", _("Iraq"))
    ("Ireland", _("Ireland"))
    ("Israel", _("Israel"))
    ("Italy", _("Italy"))
    ("Jamaica", _("Jamaica"))
    ("Japan", _("Japan"))
    ("Jordan", _("Jordan"))
    ("Kazakhstan", _("Kazakhstan"))
    ("Kenya", _("Kenya"))
    ("Kiribati", _("Kiribati"))
    ("Korea, Democratic People's Republic of", _("Korea, Democratic People's Republic of"))
    ("Korea, Republic of", _("Korea, Republic of"))
    ("Kuwait", _("Kuwait"))
    ("Kyrgyzstan", _("Kyrgyzstan"))
    ("Lao People's Democratic Republic", _("Lao People's Democratic Republic"))
    ("Latvia", _("Latvia"))
    ("Lebanon", _("Lebanon"))
    ("Lesotho", _("Lesotho"))
    ("Liberia", _("Liberia"))
    ("Libyan Arab Jamahiriya", _("Libyan Arab Jamahiriya"))
    ("Liechtenstein", _("Liechtenstein"))
    ("Lithuania", _("Lithuania"))
    ("Luxembourg", _("Luxembourg"))
    ("Macao", _("Macao"))
    ("Macedonia, The Former Yugoslav Republic of", _("Macedonia, The Former Yugoslav Republic of"))
    ("Madagascar", _("Madagascar"))
    ("Malawi", _("Malawi"))
    ("Malaysia", _("Malaysia"))
    ("Maldives", _("Maldives"))
    ("Mali", _("Mali"))
    ("Malta", _("Malta"))
    ("Marshall Islands", _("Marshall Islands"))
    ("Martinique", _("Martinique"))
    ("Mauritania", _("Mauritania"))
    ("Mauritius", _("Mauritius"))
    ("Mayotte", _("Mayotte"))
    ("Mexico", _("Mexico"))
    ("Micronesia, Federated States of", _("Micronesia, Federated States of"))
    ("Moldova, Republic of", _("Moldova, Republic of"))
    ("Monaco", _("Monaco"))
    ("Mongolia", _("Mongolia"))
    ("Montserrat", _("Montserrat"))
    ("Morocco", _("Morocco"))
    ("Mozambique", _("Mozambique"))
    ("Myanmar", _("Myanmar"))
    ("Namibia", _("Namibia"))
    ("Nauru", _("Nauru"))
    ("Nepal", _("Nepal"))
    ("Netherlands", _("Netherlands"))
    ("Netherlands Antilles", _("Netherlands Antilles"))
    ("New Caledonia", _("New Caledonia"))
    ("New Zealand", _("New Zealand"))
    ("Nicaragua", _("Nicaragua"))
    ("Niger", _("Niger"))
    ("Nigeria", _("Nigeria"))
    ("Niue", _("Niue"))
    ("Norfolk Island", _("Norfolk Island"))
    ("Northern Mariana Islands", _("Northern Mariana Islands"))
    ("Norway", _("Norway"))
    ("Oman", _("Oman"))
    ("Pakistan", _("Pakistan"))
    ("Palau", _("Palau"))
    ("Palestinian Territory, Occupied", _("Palestinian Territory, Occupied"))
    ("Panama", _("Panama"))
    ("Papua New Guinea", _("Papua New Guinea"))
    ("Paraguay", _("Paraguay"))
    ("Peru", _("Peru"))
    ("Philippines", _("Philippines"))
    ("Pitcairn", _("Pitcairn"))
    ("Poland", _("Poland"))
    ("Portugal", _("Portugal"))
    ("Puerto Rico", _("Puerto Rico"))
    ("Qatar", _("Qatar"))
    ("Reunion", _("Reunion"))
    ("Romania", _("Romania"))
    ("Russian Federation", _("Russian Federation"))
    ("Rwanda", _("Rwanda"))
    ("Saint Helena", _("Saint Helena"))
    ("Saint Kitts and Nevis", _("Saint Kitts and Nevis"))
    ("Saint Lucia", _("Saint Lucia"))
    ("Saint Pierre and Miquelon", _("Saint Pierre and Miquelon"))
    ("Saint Vincent and The Grenadines", _("Saint Vincent and The Grenadines"))
    ("Samoa", _("Samoa"))
    ("San Marino", _("San Marino"))
    ("Sao Tome and Principe", _("Sao Tome and Principe"))
    ("Saudi Arabia", _("Saudi Arabia"))
    ("Senegal", _("Senegal"))
    ("Serbia and Montenegro", _("Serbia and Montenegro"))
    ("Seychelles", _("Seychelles"))
    ("Sierra Leone", _("Sierra Leone"))
    ("Singapore", _("Singapore"))
    ("Slovakia", _("Slovakia"))
    ("Slovenia", _("Slovenia"))
    ("Solomon Islands", _("Solomon Islands"))
    ("Somalia", _("Somalia"))
    ("South Africa", _("South Africa"))
    ("South Georgia and The South Sandwich Islands", _("South Georgia and The South Sandwich Islands"))
    ("Spain", _("Spain"))
    ("Sri Lanka", _("Sri Lanka"))
    ("Sudan", _("Sudan"))
    ("Suriname", _("Suriname"))
    ("Svalbard and Jan Mayen", _("Svalbard and Jan Mayen"))
    ("Swaziland", _("Swaziland"))
    ("Sweden", _("Sweden"))
    ("Switzerland", _("Switzerland"))
    ("Syrian Arab Republic", _("Syrian Arab Republic"))
    ("Taiwan, Province of China", _("Taiwan, Province of China"))
    ("Tajikistan", _("Tajikistan"))
    ("Tanzania, United Republic of", _("Tanzania, United Republic of"))
    ("Thailand", _("Thailand"))
    ("Timor-leste", _("Timor-leste"))
    ("Togo", _("Togo"))
    ("Tokelau", _("Tokelau"))
    ("Tonga", _("Tonga"))
    ("Trinidad and Tobago", _("Trinidad and Tobago"))
    ("Tunisia", _("Tunisia"))
    ("Turkey", _("Turkey"))
    ("Turkmenistan", _("Turkmenistan"))
    ("Turks and Caicos Islands", _("Turks and Caicos Islands"))
    ("Tuvalu", _("Tuvalu"))
    ("Uganda", _("Uganda"))
    ("Ukraine", _("Ukraine"))
    ("United Arab Emirates", _("United Arab Emirates"))
    ("United Kingdom", _("United Kingdom"))
    ("United States", _("United States"))
    ("United States Minor Outlying Islands", _("United States Minor Outlying Islands"))
    ("Uruguay", _("Uruguay"))
    ("Uzbekistan", _("Uzbekistan"))
    ("Vanuatu", _("Vanuatu"))
    ("Venezuela", _("Venezuela"))
    ("Viet Nam", _("Viet Nam"))
    ("Virgin Islands, British", _("Virgin Islands, British"))
    ("Virgin Islands, U.S.", _("Virgin Islands, U.S."))
    ("Wallis and Futuna", _("Wallis and Futuna"))
    ("Western Sahara", _("Western Sahara"))
    ("Yemen", _("Yemen"))
    ("Zambia", _("Zambia"))
    ("Zimbabwe", _("Zimbabwe"))
]
